---
- 
  become: true
  block:

  - name: set timezone
    timezone:
      name: "{{ awx.tz }}"
  
  -
    name: disable firewalld
    systemd:
      name: firewalld
      state: stopped # started
      enabled: false

  
  - name: install git, ansible with epel repo
    yum:
      name:
      - git
      #- ansible
      enablerepo: epel
      #state: present
  
  - yum:
      name:
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
  
- name: create work and awx source directory
  file:
    dest: "{{ awx.work_dir }}"
    state: directory
  loop:
    - "{{ awx.work_dir }}"
    - "{{ awx.work_dir }}/src"


# AWXのソースをチェックアウト
- name: check out git resource
  git:
    repo: https://github.com/ansible/awx.git
    dest: "{{ awx.work_dir }}/src"
    accept_hostkey: yes
    version: "{{ awx.version }}"

# AWX DB Data保存用のディレクトリを作成
- name: create awx postgresql data dir
  file:
    dest: "{{ awx.work_dir }}/{{ awx.pg.data_dir }}"
    state: directory

# AWX プロジェクトフォルダ用のディレクトリを作成
- name: create awx project data dir
  file:
    dest: "{{ awx.work_dir }}/{{ awx.project_dir }}"
    state: directory

# # AWXインストール時にインベントリ変数を上書きするためのgroup_varsフォルダを作成
# - name: create group_vars dir
#   file:
#     dest: "{{ awx.work_dir }}/src/installer/group_vars"
#     state: directory
# 
# # AWXインストール用の変数を展開
# - name: overwrite awx inventory variable
#   template:
#     src: all.j2.yml
#     dest: "{{ awx.work_dir }}/src/installer/group_vars/all.yml"
#     mode: 0640


- name: edit inventory file
  shell: |
    cd {{ awx.work_dir }}/src/installer
    sed 's/^\([^#][^ ]*=\)"*\([^"]*\)"*$/\1"\2"/' inventory > inventory.new && { 
    mv inventory     inventory.orig
    mv inventory.new inventory
    }
  args:
    creates: "{{ awx.work_dir }}/src/installer/inventory.orig"



- debug:
    msg: |
      kitchen login
      cd src/installer
      sudo ansible-playbook -i inventory install.yml
      ^d
      open -a /Applications/Safari.app http://localhost:8080/
      ユーザ名：admin, パスワード：password
