---

-
  become: true
  block:
    
  - name: install epel-release
    yum:
      name: epel-release
      state: present
  
  # - get_url:
  #     url: https://bootstrap.pypa.io/get-pip.py
  #     dest: /tmp/get-pip.py
  # 
  # - name: install pip
  #   shell: cat /tmp/get-pip.py | /bin/python2.7
  #   args:
  #     creates: /bin/pip
  
  - name: install pip
    shell: curl -kL https://bootstrap.pypa.io/get-pip.py | python
    args:
      creates: /bin/pip
  
  - name: install docker-py
    pip:
      name: 
      #- docker
      #- docker-py
      - ansible 
      - docker-compose 
      - selinux
